### ISSUE TITLE
ERROR in OfflinePlugin: Something went wrong with ServiceWorker entry

### ISSUE THREAD

**Issue by mediabakery** [NekR/offline-plugin#10]
I tried to use your offline-plugin, but I got an error message. Can you help me please?
The only hint is: **ERROR in OfflinePlugin: Something went wrong with ServiceWorker entry**

The plugin produces some files 
- appcache/*
- __offline_serviceworker.0317e3e194f425aca189

This is my config file: https://gist.github.com/anonymous/9a95e4ebeb7f1868e03b

I would be very grateful if you can give me a hint on what I'm doing wrong.

**Comment by NekR** [comment]
@mediabakery thanks for reporting this!

Issue happens here https://github.com/NekR/offline-plugin/blob/master/src/service-worker.js#L53 because I do exact check for `__offline_serviceworker` few lines above, but it of course does not works since you are using hash in chunks. There probably should be a better way to produce fake entries, or I may not need them at all.

Anyway, I will have a fix today.

**Comment by NekR** [comment]
Btw, in your case, do you want ServiceWorker output file to have hash in its name?

**Comment by mediabakery** [comment]
@NekR Thanks! Yes you are right. I don't need to hash the serviceWorker file name.

**Comment by NekR** [comment]
@mediabakery I just pushed the fix, it works for me, but can you try it before I publish it to npm?

To test latest update, install `offline-plugin` directly from GitHub repo:
```npm install https://github.com/NekR/offline-plugin```

**Comment by mediabakery** [comment]
@NekR Thanks! I'll test it as soon as possible!

**Comment by mediabakery** [comment]
Hey @NekR. It works for me as expected. Thanks!

**Comment by NekR** [comment]
Great, thanks for reporting this one!

**Comment by NekR** [comment]
Published on `npm`
