### ISSUE TITLE
offline plugin not caching all the assets

### ISSUE THREAD

**Issue by nawrasbaghdadi** [NekR/offline-plugin#108]
please can you check this issue 
https://github.com/kentcdodds/es6-todomvc/issues/21#issuecomment-248109710

**Comment by NekR** [comment]
@nawrasbaghdadi Yes, I'm aware of that. I just don't have time right now to handle that.

**Comment by NekR** [comment]
@nawrasbaghdadi sorry for the delay, I was busy last days. I'm going to solve your issue today. Thanks for understanding.

**Comment by NekR** [comment]
@nawrasbaghdadi Okay, I made a project based on your project's `app/` subfolder, it's here: https://github.com/NekR/offline-plugin__test-project

It uses all your code (slightly modified only in `webpack.config.babel.js`) and generated correctly what you need. 

First, clone repo with git. Then run `npm install` to install dependencies and then run `npm run build` to build with webpack.

**Comment by nawrasbaghdadi** [comment]
@NekR thanks for your help , I just deploy it on surge it return error "NetworkError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
", it is looking for `sw.j` from the root, not in `dist` folder , you can check 
https://super-holiday.surge.sh/

**Comment by NekR** [comment]
Right, because your output folder 'dist/' so it's a root for both webpack and `offline-plugin`. If on a server it's a `/dist/` subfolder, then you should tell about that in config (by setting `publicPath`). See this commit: https://github.com/NekR/offline-plugin__test-project/commit/64ca13708a40ebdab1de2b2a872adcc063038007

Also you shouldn't register SW manually when you add `require('offline-plugin/runtime').install()` because `offline-plugin` does it for you. So I removed your manual registration now: https://github.com/NekR/offline-plugin__test-project/commit/70d54fb97a434a3d78ed433a6fa590aa8d57a496

And the last, even though these paths are added to generated SW:

```
'app/images/bgz.jpg',
'app/images/hamburger.svg',
'app/images/logo_grey.svg',
```

SW won't be able to cache them because a) path is wrong, it must be e.g. `/images/bgz.jpg`; b) SW cannot cache assets outside its folder and it's in `/dist/` folder but images in `/images/`.

You are clearly doing things wrong with webpack here. Basically, you shouldn't organize structure of your project as it's now. I'm not going to describe how exactly, but current structure is not best.

There is a way to handle that as is with current structure in `v4` of offline-plugin, but it's still in development. If you are okay with that, I can show you how to handle it with `v4`.

**Comment by nawrasbaghdadi** [comment]
@NekR , so I did remove the `dsit` folder from the `webpack.config` also the `publicpath` so now it is serving from the root, not from `dist` .now it is caching the assist I wanted but not serving it off-line . `https://equal-motion.surge.sh/` check this and you can see that all working and off-line application is running but when you go offline it not working .

**Comment by NekR** [comment]
@nawrasbaghdadi sure. Do you cache pre `/` path to go offline? If not, how it can go offline without html page being cached?

**Comment by nawrasbaghdadi** [comment]
@NekR thanks , yes it is working , but I thought it automatically caches everything in the root folder so the HTML should be automatically cached. how I did it now is adding `/` to the `caches:` object and `externals` so is there is any other way ?

**Comment by NekR** [comment]
@nawrasbaghdadi it automatically cached everything **generated by webpack**. If you generated html files by webpack, sure, they will be automatically cached. 

> how I did it now is adding / to the caches: object and externals so is there is any other way ?

This is the correct way because `/` is external asset (not generated by webpack), so it has to be added manually.

**Comment by nawrasbaghdadi** [comment]
@NekR , thanks for your help , i will be waiting for `v4`

**Comment by NekR** [comment]
@nawrasbaghdadi if you are already solved it with reorganizing the structure then you don't really need `v4`. I mean, with `v4` it will be easier if course, but it won't solve the issue `/` not being added automatically.

**Comment by nawrasbaghdadi** [comment]
@NekR yes I solve it , but I will look how to generate HTML form webpack .
why I need `v4` coz I will use this plugin but I don't want to be forced to use the same file structure

**Comment by NekR** [comment]
Okay, I'm closing this. I'll let you know once `v4` is ready and show how it can solve your problem. Thanks for reaching out.
