### ISSUE TITLE
Why is "onUpdating" not supported for appcache?

### ISSUE THREAD

**Issue by MoOx** [NekR/offline-plugin#111]
I was previously using 

```js
window.applicationCache.addEventListener(
  "downloading", this.handleDownloading, false
)
```

I guess we could use this too for the same event?

**Comment by MoOx** [comment]
Saying that because of this https://github.com/NekR/offline-plugin#onupdating where I can see 
"onUpdating

Not supported for AppCache"

But is seems it's supported https://github.com/NekR/offline-plugin/blob/251973e92745506170d04f7ed19fb9feac2098b3/tpls/appcache-frame.tpl#L59

**Comment by MoOx** [comment]
So maybe it's just a doc issue :D

**Comment by NekR** [comment]
> So maybe it's just a doc issue :D

Nope. It's supported, indeed, but is commented away here: https://github.com/NekR/offline-plugin/blob/251973e92745506170d04f7ed19fb9feac2098b3/tpls/appcache-frame.tpl#L125

The reason for that is that we cannot distinguish between `downloading` being fired for updated or for the initial install. At least it's very hard with current registration approach: via iframe.

Even if it's possible by doing checks inside `runtime.js` instead of iframe `.html` file, it's too much work for _deprecated technology_. Interesting thing is that I spend a lot more time on AppCache implementation here, than on ServiceWorker one. So I kind-of not interested in that feature (I personally believe AppCache shouldn't be used at all).

So I see 2 ways to handle this:

1) Expose `onUpdating` as is (with false positives)
2) Someone implements detection between _install downloading_ and _update downloading_

**Comment by MoOx** [comment]
Nevermind, I agree that Appcache is the past. Your explanation is fine.

**Comment by NekR** [comment]
I think I can add reference to this issue in readme after the note about
AppCache. Just to prevent other confusions.
