### ISSUE TITLE
Compatibility with wepback-dev-server

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#131]
Current state of compatibility with `wepback-dev-server` is unknown. Any feedback is welcome.

Things to solve:
* Should it work in normal (inline) mode? 
* Should it work somehow with hot reloading?
* Should it be there but don't handle caches/fetches? (to allow development of push notifications for example)
* Something else?

**Comment by RayBenefield** [comment]
First of all thank you for setting this up as it made implementing Service Worker take next to no time at all (literally installed and I was good). The only time I spent was how to setup `sw-toolbox` with this and it was truly as simple as adding the `ServiceWorker.entry` field and I was done.

One thing I've been experiencing is how frustrating loading from the cache during development is. Right now I tend to comment out this plugin, but I require it right now to initialize the service worker and then setup my toolbox routes (so I can have the offline caching for train commutes. So I definitely think that initialization of the sw should still be there for other reasons like push notifications, runtime caching, etc. In my experience these past couple of days, the precaching capabilities of the caches that are managed by this plugin should be disabled though.

I noticed the need for this this morning when I `git stash apply`, nothing visually was changed while my `webpack-dev-server` was running, then I unregistered my service worker and cleared the storage in devtools to refresh and see the changes.

Granted I just started working with the entire react/webpack setup since the end of November, so I might be missing some key details in my workflow.

Again though, thanks for making Service Workers a no brainer implementation. :)

**Comment by NekR** [comment]
Hey @RayBenefield! Yes, I feel your frustration here.

Indeed `Update on reload` helps, I think I may need to add that to the docs or at to the FAQ. That's great that you discovered it, but it's definitely not easy to find. Apart from it, let me provide some other useful things which may help you in dealing with `offline-plugin` in development:

* If you are using different webpack configs for development and production, then you can just omit `OfflinePlugin` in development config. It's fine to do so and won't affect `require('offline-plugin/runtime').install()` since it's no-op when plugin isn't added to configuration. This will make SW to not install in development mode, which might be no-go if you need to work with push notifications or other events.
* If you specify `process.env.NODE_ENV` in your config (via `DefinePlugin`) then you can use it to determine development mode and force-refresh SW and the page:

```js
const offline = require('offline-plugin/runtime');

if (process.env.NODE_ENV === 'development') {
  offline.install({
    onUpdating: () => {
      console.log('SW Event:', 'onUpdating');
    },
    onUpdateReady: () => {
      console.log('SW Event:', 'onUpdateReady');
      offline.applyUpdate();
    },
    onUpdated: () => {
      console.log('SW Event:', 'onUpdated');
      // Force reload the page
      window.location.reload();
    },

    onUpdateFailed: () => {
      console.log('SW Event:', 'onUpdateFailed');
    }
  });
} else {
  offline.install();
}
```

That's might be really helpful for all use cases and the best built-in support of `webpack-dev-server`, but while it's not supported correctly those 2 ways might be possible solutions for someone.

> Again though, thanks for making Service Workers a no brainer implementation. :)

Thank you! You are definitely very welcome :-)

**Comment by NekR** [comment]
Tracking in #138
