### ISSUE TITLE
Support for credentials: include

### ISSUE THREAD

**Issue by unsafecode** [NekR/offline-plugin#134]
I have faced a strange issues lately with the SW generated by the plugin: it looks like cookies are NOT sent by default, as the Fetch specification states.

The problem lies in our webserver, that requires a kind of session cookie to download cached assets. Kind can be done by specifying `{ credentials: "include" }` in the [SW template](https://github.com/NekR/offline-plugin/blob/master/src/misc/sw-template.js#L365).

It would be nice very to have an additional configuration option to enable that.

**Comment by NekR** [comment]
@unsafecode Yes, you are totally right. 

It's actually fixed/added in `v4`. See here how to install `v4`: https://github.com/NekR/offline-plugin/pull/109

This issue was originally reported here: https://github.com/NekR/offline-plugin/issues/121

You may use it as follows:

```js
new OfflinePlugin({
  ServiceWorker: {
    prefetchRequest: { credentials: 'same-origin' },
  },
})
```

Here is the issue to make `credentials: 'same-origin'` the default value: https://github.com/NekR/offline-plugin/issues/123

I also recommend setting it to `same-origin` if you just need credentials on your origin, because `include` allows it on cross-domain too.
