### ISSUE TITLE
Are AppCache events unstable?

### ISSUE THREAD

**Issue by tribou** [NekR/offline-plugin#140]
First off, outstanding work on the 4.x releases!  I think this plugin is becoming much more intuitive. 😄 

I was curious why you warned against using AppCache events in the README?  I was testing on Safari 10, and at least the `onUpdateReady` appears to be firing without fail.  Is it just because it hasn't been thoroughly tested on older browsers?  I haven't tested in IE/Edge yet either...

**Comment by NekR** [comment]
> First off, outstanding work on the 4.x releases! I think this plugin is becoming much more intuitive. 

Thanks, trying to do so :-)

> I was curious why you warned against using AppCache events in the README? ...

AppCache events are unstable because they behave differently in different browsers and some hacks are applied to make it work as it works now. I actually tested them on all old and new browsers and took so much time, even more than it took to write whole `offline-plugin`'s ServiceWorker. Those events are unstable because I don't know when they may fail and why because it's AppCache. There are some chances that some events may fire twice for example. Mostly problems here are because AppCache is loaded in iframe and every browser behaves different in such case (regarding events). 

In general, those events work and should work fine. But don't expect them to be bulletproof or something like that. This is why they are marked unstable.

**Comment by tribou** [comment]
Great explanation. Thanks!
