### ISSUE TITLE
[question] vary assets according to browser features?

### ISSUE THREAD

**Issue by jampy** [NekR/offline-plugin#149]
This is more a theoretical question.

Since my application targets mostly *(but not exclusively)* very up-to-date Chrome browsers, I want make use of new features like native ES6 features, native `async`/`await` support where available - but still support browsers that don't.

First of all, this means that I need two completely different builds / bundles. That's relatively easy to do with Webpack. Luckily, since I have [unique asset file names](https://www.npmjs.com/package/webpack-stable-module-id-and-hash) (`sw.js` being an exception), file names are no problem, either.

Second, there must be some sort of runtime feature detection that runs on the client (browser). That should be easy to do with very few code lines.

The tricky part is how to make this work with `offline-plugin`.

Obviously, it wouldn't make sense to offline-cache *all* build variants in the browser, so there must be some more logic *server-side* that switches bundles (ie. `sw.js` version) as needed.

I learned (from you :-) ) that the service worker URL should never be altered, so passing feature-information in query strings is not possible. I think the only way (if at all) is to pass the information via custom HTTP headers to the server.

So, assume there is a way to add custom code **to `sw.js`** (this is just an example to make clear what I mean):

```javascript
function getUserDefinedHeaders() {

  // --- feature detection ---
  var feat = {};

  try {
    eval('var x = async function(){ await x() };');
    feat.asyncAwait = true;
  } catch (e) { /* ignore */ }

  // --- define header ---
  return {
    'X-Browser-Features': encodeURIComponent(JSON.stringify(feat))
  }

}
```

Now, before the `offline-plugin` Service Worker makes the `sw.js` server request to check if there is a new version, it would add HTTP headers returned by `getUserDefinedHeaders()`.

The server could choose which version of `sw.js` to serve based on the `X-Browser-Features` header received. If I'm not wrong this is all it takes* to switch from one bundle to another, since all other assets are defined within `sw.js`.

**for the sake of simplicity, let's ignore edge cases like initial load (first visit) and the index page for a moment*

For example, let's say that a user just updated to Chrome 55 ([with native async/await support](https://www.chromestatus.com/feature/5643236399906816)) so that the code above detects `feat.asyncAwait === true`. As soon as my PWA is opened, the Service Worker will send it's usual `sw.js` request. But now the server responds with a *different* (pre-built) `sw.js` content which contains completely different hashes ans URLs. The service worker will download a bunch of new assets and start the switchover when done (just like when I deploy a new release).

Of course this would need slight modifications of `offline-plugin` itself, but first it would be interesting to know if such a technique could work at all.

Since you're more experienced with service workers and similar: do you think this could work? Or perhaps do you know a better way to do this?

*PS: An alternative could be to check the user agent, but I don't like that idea that much*

**Comment by NekR** [comment]
@jampy hey! Sorry, I'm totally busy with my current work projects. There is a lot of thinking/consideration needed here and unfortunately I don't have time for it right now. I think we will be able to fix all your issues with `offline-plugin` in January :-)

**Comment by jampy** [comment]
@NekR, okay, I understand that

Best wishes and looking forward to hear from you soon! :-)

**Comment by jampy** [comment]
@NekR: any news on this?

**Comment by NekR** [comment]
Sorry for a delay.
So, I think the best way to do it is to avoid directly involving SW into it. If you want to put parts of this logic to SW then you will need to sync feature detection between main script and SW itself, e.g. if you will need DOM detection.

But there is a problem with it of course -- you cannot download those scripts on SW install because you don't know the correct params for them. I see two ways here for it:

* Exclude scripts from the SW install (`offline-plugin` main cache) and cache those scripts when they are requested (put them into optional cache of `offline-plugin`). This way it possible to calculate needed features and do needed request on first visit, i.e. `/bundle.js?native-async=true`. To cache these scripts when SW installed you will need to listen on install event on main thread (`offline-plugins` onInstalled/onUpdated events) and do additional request with correct params from main thread, e.g.:
```js
onInstalled() {
  fetch('/bundle.js?native-async=true');
}
```
* Kind of the same as previous: you calculate correct feature params on the main thread and request scripts with them normally. But to cache correct scripts in SW you have custom SW logic (via `ServiceWorker.entry` option of `offline-plugin`) for `install` event. What you need to do in that event is to ping main thread and ask it for a correct feature params, wait for them and then cache scripts with correct params.

In the second case you probably can do feature params calculation in SW itself and avoid pining the main thread, if you are okay with it.

In a this cases SW code and SW file stays the same, you just return correct bundles from the server. And yes, `offline-plugin` ignores your query params for generated assets when do caching, so you can request them with whatever query params and they will be cached normally.

I hope it helps :-)

**Comment by jampy** [comment]
Hi @NekR 

thanks for your explanations and sorry for the late reply.

>then you will need to sync feature detection between main script and SW itself, e.g. if you will need DOM detection.

I don't need DOM, I just need JavaScript feature detection like mentioned in the original post. That can be done safely in the SW as it's using the same engine (the thread doesn't matter).

I appreciate your ideas, but I don't think they will work in cases like mine since the feature detection practically affects **all** scripts, not just some optional scripts. This is because I'd like to have 2-3 versions with different Babel transpiler settings. That will cause those builds to become completely different. That is something about 1-2 MB Javascript assets in 15 files (yeah, it's a large application).

IMHO all I need is a simple header that is sent to the server the moment `sw.js` is checked for updates.

Let me clarify:

Say I have two Babel configurations:

- configuration `legacy` for older browsers, based on ES5
- configuration `modern` for modern browsers like Chrome 56 supporting Promises, `async`/`await`, arrow functions etc.

This will generate two large builds, each with unique named assets like `legacy-11-chunk-8-53-10849c310f1eaf13c54b6f0ea-en.js` and `modern-11-chunk-8-53-10849c310f1eaf13c54b6f0ea-en.js`.   

The `sw.js` file generated by `offline-plugin` will be **renamed** post-build to `sw-legacy.js` and `sw-modern.js`, depending on the resp. build settings. For the public web, this is still `sw.js`.

When the `offline-plugin` SW contacts the server to check for updates, it will somehow magically (via a HTTP header?) if the "modern" features is supported. The feature-detection is done by the SW itself, since it's just JavaScript language leven feature detection.

The server will reply with metadata and contents for `sw-legacy.js` **or** `sw-modern.js`, depending on the flag. Since the contents refer to completely different asset URLs, the `sw.js` pratically acts as a switch for the whole application.

This could work if `offline-plugin` could provide a hook in conjunction with a custom `ServiceWorker.entry`-like module that provides the feature detection.

Say there is a *custom* module `sw-feature-detection.js` (or a module like [sixflix](https://github.com/bevacqua/sixflix/blob/master/index.js) is used):

```
function getUserDefinedHeaders() {

  // --- feature detection ---
  var feat = {};

  try {
    eval('let x = async () => { await x() };');
    feat.asyncAwait = true;
  } catch (e) { /* ignore */ }

  // --- define header ---
  return {
    'X-Browser-Features': encodeURIComponent(JSON.stringify(feat))
  }

}

export default getUserDefinedHeaders;
```

...and it is activated in the `offline-plugin` configuration like so:

```
    new OfflinePlugin({
        updateStrategy: "changed",
        /* ... */
        ServiceWorker: {
          events: true,
          customHeadersHook: "path/to/sw-feature-detection.js"
        }
    })
```

It would be ideal if `customHeadersHook()` headers would be used for *all* server requests, so that the server could also serve the correct Index page (the root URL) .

What do you think?
