### ISSUE TITLE
uncache versioning

### ISSUE THREAD

**Issue by zackify** [NekR/offline-plugin#160]
If I don't remove the version, my assets load over the network. Am I supposed to do System.import in webpack with the cache version appended? How is that supposed to work.

**Comment by NekR** [comment]
I'm not sure what you mean. What versioning exactly you want to remove? What works wrong and loads from the network? Also, is #159 solved or it's somehow related to this?

**Comment by zackify** [comment]
Sorry. I was up way too long last night haha. Let me explain better. I have everything working now. Except one problem. If I do not set version to () => null, in chrome, the devtools show every bundle split being loaded with the uncache parameter. When I go to a new page and load a code split, it is loaded without the uncache parameter and thus it is not served from the cache. Setting the version to null causes everything to be loaded from the service worker. I will debug this a little more today but is couldn't find an issue that had this problem.

**Comment by NekR** [comment]
Thanks for explanation :-)

> When I go to a new page and load a code split, it is loaded without the uncache parameter and thus it is not served from the cache.

That's not true. Having a the `__uncache` parameter or any other query params in request doesn't affect if resource is loaded from the cache or not by `offline-plugin`. It's loaded from the cache if it's cached.

> I will debug this a little more today but is couldn't find an issue that had this problem.

Because there is no problem with it I guess. Everyone has `__uncache` param and I in my projects too and everything loads from SW fine.

> () => null

I think I need to start throwing an error when people do it. There is 0 reason to do so.

Here you may find a bit more info about `__uncache` parameter: https://github.com/NekR/offline-plugin/issues/127

**Comment by zackify** [comment]
So I think I may have it all working today. The issue instead might have
stemmed from the fact that up until yesterday I was doing folder based
hashes. Seems to be weird problems when doing that. Thanks for the help!

**Comment by NekR** [comment]
@zackify sure, no problem. It still would be good if you read that issue, there is a lot useful info about `__uncache`. But basically it shouldn't affect in any way because it used only to bust http/proxy cache on SW install (assets precaching).

I'm going to close this, but feel free to open or create another issue if something. Thanks :-)

**Comment by NekR** [comment]
@zackify You mean you were settings webpack' `output.publicPath` this way: `publicPath: '/assets/js/' + hash + '/'` or how?

**Comment by zackify** [comment]
Yes, like this. Changing it fixed everything.
```
output: {
    path: __dirname + `/../public/assets/js/${process.env.COMMIT_HASH}/`,
    filename: '[name].js',
    chunkFilename: '[id].js',
    publicPath: `/assets/js/${process.env.COMMIT_HASH}/`,
  },
```

**Comment by NekR** [comment]
@zackify hmm.. that's supposed to work just fine. And it's weird that `version: () => null` helped with it. Maybe you can share your webpack config so I could debug it? If you aren't comfortable to place it in public, then you may send it to my email (it's on my GitHub profile page).

**Comment by zackify** [comment]
Like I said, I have gone away from that and had already spent a long time pulling my hair out on it. I think its related to this possibly but it's not a problem anymore http://stackoverflow.com/a/39606127/1487687

**Comment by NekR** [comment]
Okay
