### ISSUE TITLE
Question: separate public path for routes

### ISSUE THREAD

**Issue by nicksrandall** [NekR/offline-plugin#222]
Hi, first off, thanks so much for support this plugin!

I'm wondering if there is a way to make this plugin support my use-case:

Let's say I have all my public assets (JavaScript/CSS) served from `www.example.com/static`
my "Single Page Application" is rooted to `www.example.com/render` such that any requests to `www.example.com/render/**/*` will always fallback to serve the base HTML that is at `www.example.com/render/` and the Javascript will handle the routing past that.

Is is possible to configure this plugin to cache both routes so that I can get true offline support?

Would I need ANOTHER service worker to handle the SPA?

Thanks again for any help!

**Comment by GGAlanSmithee** [comment]
@nicksrandall see if [the SPA example](https://github.com/NekR/offline-plugin/blob/master/docs/examples/SPA.md) can be of help. You'd have to use the correct `publicPath` for your configuration / application.

**Comment by NekR** [comment]
> Would I need ANOTHER service worker to handle the SPA?

You certainly do need more than one ServiceWorker. What you need is to make your `sw.js` be in root of your website, i.e. `/sw.js`, this was it will be able to cache both places. 

Also you will need to configure `ServiceWorker.navigateFallbackURL` or `cacheMaps` option.  For that see already mentioned SPA example and this https://github.com/NekR/offline-plugin/blob/master/docs/caches.md.

**Comment by pdiniz13** [comment]
I'm having the same issue. I tried following the SPA example the problem is that my assets are being server out of static while the app is being server out of '/' If I set publicPath: '/' then the serviceWorker tries to fetch the static files at '/' instead of '/static'.  If I set it to publicPath: '/' then  it doesn't fetch the index file at '/'. I tried using 
```          rewrites: (asset) => {
              // This is code from default rewrites() function, feel free to remove it
              // if not needed
              const newAsset = asset.replace(/^([\s\S]*?)index.htm(l?)$/, (match, dir) => dir || '/');
              console.log(newAsset);

              if (newAsset === '/') {
                  console.log('fired');
                  return '/';
              }

              return prepend + newAsset;

          },```
but that didn't work either.

**Comment by NekR** [comment]
ServiceWorker cannot cache things outside of its scope. If you generated it into `/static/` then that's its scope and it cannot cache `/`. You need to generated `sw.js` into `/` and your assets into `/static/`, easiest way to do it is by settings webpack's `output` path to your dist folder and setting `filename` option to `static/[name].js` or something like that.  If you generated other assets with wepback, e.g. images, then it might be trickier this way.

Another way to leave everything is as, set `offline-plugin`'s `ServiceWorker.publicPath` option to `/sw.js` and manually move `sw.js` out of `static/` folder to the parent folder after the build.

You didn't provide more information, so that's all what I can suggest.

**Comment by pdiniz13** [comment]
This is what ended up working for me
```    new OfflinePlugin({
      safeToUseOptionalCaches: true,
      publicPath: '/',
      updateStrategy: 'changed',
      ServiceWorker: {
        publicPath: '/sw.js',
        events: true,
        // navigateFallbackURL: '/',
        entry: './src/sw-handler.js'
      },
      AppCache: false,
      rewrites: (asset) => {
        // This is code from default rewrites() function, feel free to remove it
        // if not needed
        const newAsset = asset.replace(/^([\s\S]*?)index.htm(l?)$/, (match, dir) => dir || '/');

        if (newAsset === '/') {
          return '/';
        }

        return `/client-assets/${newAsset}`;
      },
    })```
I set the path for the serviceWorker itself and the app root to '/' and switched all of the other ones to 'client-assets' This wasn't perfect since my other routes that I would like to server render wouldn't cache and in the end I ended up deciding to not cache the server render since it was having several auth and other related issues. But just posting it here in case someone else wants to try it.

**Comment by NekR** [comment]
Not sure if that's the best way, but good if it works for you. Thanks @pdiniz13!
