### ISSUE TITLE
offline-plugin not working for SPA app served locally

### ISSUE THREAD

**Issue by tsnieman** [NekR/offline-plugin#229]
- [**Example repo**](https://github.com/tsnieman/webpack2test/tree/offline-plugin_help1). Make sure you're using the `offline-plugin_help1` branch. Start it using `npm start:prod` (or `yarn start:prod`), wait for the build, then navigate to `http://localhost:4200`.

- [Configuration for offline plugin can be seen here](https://github.com/tsnieman/webpack2test/blob/ee7e86fce40a5162a37910b863ccc5f48f3d6400/config/webpack.config.prod.js#L97-L137)

- [OfflinePluginRuntime initiated here](https://github.com/tsnieman/webpack2test/blob/ee7e86fce40a5162a37910b863ccc5f48f3d6400/src/index.jsx#L9-L30)

# What _is_ working :heavy_check_mark: 

- Some assets seem to be getting cached
![image](https://cloud.githubusercontent.com/assets/595711/24842284/17755168-1d4a-11e7-98c6-c0c3f95edb8e.png)

# What _isn't_ working :x:

- Reloading the page after checking the "Offline" box results in the "no network connection (dinosaur) page" in Chrome
![image](https://cloud.githubusercontent.com/assets/595711/24842294/3ba21792-1d4a-11e7-91cf-5090dc45b7bf.png)
(reload)  
![image](https://cloud.githubusercontent.com/assets/595711/24842300/5678a400-1d4a-11e7-8b7d-4af27a992b67.png)

# What I've tried

- I've tried following the [SPA.md](https://github.com/NekR/offline-plugin/blob/master/docs/examples/SPA.md) guide to the dot - with the same problem as described above.

- I've tried copying implementations from https://github.com/NekR/offline-plugin-pwa - with the same problem as described above.

# So...

Why doesn't my app cache for use when the "offline" box is checked?

Guesses that I suspect might be causing issues:
- Does it have to do with my `index.html` page not being cached/configured properly?
- Is it maybe something to do with this being localhost...?

Any help would be much appreciated. Thanks for your time.

**Comment by zouhir** [comment]
Hi @tsnieman 
Your guesses might be correct, it's great that you shared the weback configs too!

What might solve your problem is copying the `index.html` from `src` to `public` and for that I usually use `copy-webpack-plugin` used probably be like:

```
new CopyWebpackPlugin([
      { from: 'index.html'}
    ]),
```
and in your offline-plugin configs please uncomment `index.html`:
```
      caches: {
        main: [
          'commons.bundle.js',
          'vendor.bundle.js',
          'app.bundle.js',
          'index.html',
        ]
```

Now my only concern is your Web Server configs, is its entry point `localhost:4200/public` or `localhost:4200/` the `index.html` that you want offline has to be as a result of some URL fetch. if you want `localhost:4200/` to be avaialble offline then `/public` has to be your server root / entry point.

Service Worker runs fine on Localhost - it's the only place that SW doesn't need `HTTPS` to work

Keep us posted if any further help is needed!

**Comment by NekR** [comment]
Hi @tsnieman, as @zouhir mentioned, you have a problem with your server config/files structure. 

> Does it have to do with my index.html page not being cached/configured properly?

Yes, but not only that.

Fist of all, you have to uncomment `index.html` here otherwise it won't in any situation. 
https://github.com/tsnieman/webpack2test/blob/ee7e86fce40a5162a37910b863ccc5f48f3d6400/config/webpack.config.prod.js#L109
Second, you may want to move the `:rest:` to your `main` section or at least `additional`, because putting page scripts into `optional` cache may not cache them on first load. https://github.com/tsnieman/webpack2test/blob/ee7e86fce40a5162a37910b863ccc5f48f3d6400/config/webpack.config.prod.js#L117

About server now. You generated everything into `public/` folder, e.g. `index.html`, SW/AppCache and other JS/CSS assets, but use it as some sort of `static`/`assets` folder while serving your webapp on `/`. You apparently make `index.html` load from `/` like it's there, not `public/`. That's some weird manipulation on server side which cannot be known by `offline-plugin` upfront.

1. `offline-plugin` caches `/public/` when you specify `index.html` in it because this is where you generate your `index.html` and how `offline-plugin` assumes its place.
2. You register ServiceWorker on from `/public/sw.js` so ServiceWorker's scope is `/public/`, i.e. it cannot cache/handle anything outside of that folder.

This is how you can fix `offline-plugin` config, but besides that, you will have to correctly serve files from required location, i.e.: ServiceWorker file at `/sw.js` and AppCache files starting at `/appcache/`:
```js
new OfflinePlugin({
  safeToUseOptionalCaches: true,

  caches: {
    main: [
      'commons.bundle.js',
      'vendor.bundle.js',
      'app.bundle.js',
      '/',
      ':rest:',
    ],
    additional: [
      ':externals:',
    ],
  },

  externals: [
    '/'
  ],

  ServiceWorker: {
    events: true,
    navigateFallbackURL: '/',
    publicPath: '/sw.js'
  },

  AppCache: {
    events: true,
    publicPath: '/appcache',
    FALLBACK: {
      '/': '/index.html'
    },
  },
})
```

But, what I would recommend in general is to just generate correct files structure on webpack level and don't do weird manipulations on the server, this way you and we would have much less headaches :-)

**Comment by tsnieman** [comment]
Ahhh, you guys rock. Thanks @zouhir @NekR. Reworked my static asset strategy (server config) and tweaked the OfflinePlugin settings and it seems to be working fine now! Here's a basic commit with the changes for anyone who might want/need it: https://github.com/tsnieman/webpack2test/commit/96418926feddfd276bf238494e7ff28941216b33
