### ISSUE TITLE
Browser not receiving an updated SW

### ISSUE THREAD

**Issue by tleunen** [NekR/offline-plugin#235]
It looks like some users of my app sometimes don't receive an event for an updated SW. Do you have an idea of what can cause that?

Inside the Application > SW tab in chrome, the status is activated and running, but with an old SW instead of the most recent one. It doesn't see there's a new SW to load/activate.

**Comment by NekR** [comment]
Maybe you case your `sw.js` which you shouldn't do. That isn't really related to `offline-plugin`, SW update/refetch happens automatically by the browser. The only reason why it may not update your browser is because the one it just fetched is the same it has. So, you're either don't update SW file on your server or it's cached in the browser because you serve it with HTTP cache headers.

**Comment by NekR** [comment]
What I mean is that you should try that first, if that isn't the case then I hardly it as a `offline-plugin` problem, but we can try to debug that somehow if you would provide more info.

**Comment by tleunen** [comment]
Sure. Unfortunately I don't really have the time to debug it so I'll disable it for now and will get back at it asap.

I'll check the headers for `sw.js`. Maybe there were something wrong there. But it seems that even with an hard refresh, some users didn't get the new sw.js file. And I know there's a new one because other users got the new one.

It's also hard to debug because I've not experienced it myself yet.
