### ISSUE TITLE
Always fetch index.html and only serve cached version when offline

### ISSUE THREAD

**Issue by xlc** [NekR/offline-plugin#24]
Currently I place index.html to main assets and it is an external file. When I update it, because service worker script always serve it from the cache so the client will not see the new version. 

I think we need an option to specify entry files and always fetch them while online. Only serve the cached version if the fetch failed.

**Comment by xlc** [comment]
The issue maybe my incorrect configured cache policy that caches service_worker.js forever so browser won't to get new version of it without a force reload.

**Comment by NekR** [comment]
This sounds like a good point, indeed, changing external files do not affect cache updating at a moment. This makes `ServiceWorker` more like `AppCache`, which is not good. But allowing different network strategies for `main`/`additional` cache means that `AppCache` won't support it. So, even if I will be able to correctly manage this issue, then it will work for `ServiceWorker` (`AppCache` auto disabled).

**Comment by NekR** [comment]
@xlc I use it production site, but in my case everything what is passed to `offline-plugin` is updated on every build, so I have no problem with it. But I see your problem.

The idea of `offline-plugin`, at a moment of first release, was to satisfy my own needs, i.e. be workable for static web-apps with some API usage. Of course, this doesn't solve all the use cases and also thought recently about similar problem you have encountered. And I can assure you, it's more complex than that you have described.

Unless everything is updated with each build (SW/AppCache update), you will always have version collisions, even if your use cases will be solved, your users may have situation when some files are of old version, and some of new.

One absolute solution is to check _everything_ for version compatibility with SW. And this is big project. I would be good to have it for v3, but I am not sure.

Btw, if your `index.html` points to something with `[hash1]` but on server everything is with `[hash2]`, then you will have problems even without SW.

Also, what type of `updateStrategy` you are using?

**Comment by NekR** [comment]
Okay, I just checked the SW code and deletion of old caches happens only in `activate` event, this means that all old pages with old SW are unloaded and only pages which server new SW are active. So if `index.html` was updated with a build, then for new clients new `index.html` should be served.

**Comment by xlc** [comment]
We are using `hash` updateStrategy. I am very confused about service worker now... Especially refresh in Chrome won't kill the old service worker and only close tab will, I have multiple service worker instance serving different version of the files in different tabs...

**Comment by NekR** [comment]
Okay, `hash` strategy is fine. Just update everything with each build and all will work.

> I have multiple service worker instance serving different version of the files in different tabs...

SW is guarded agains that and it won't do it unless you coded so. There is only one active SW at a time and new SW (waiting one) doesn't take control of any old pages, it becomes active only when all old pages are closed and old SW is unloaded.

This is how it's coded in this plugin and how it's by default.

**Comment by Hengjie** [comment]
@NekR so re what you said in https://github.com/NekR/offline-plugin/issues/24#issuecomment-182790783 basically index.html will not update for an existing user with SW installed, unless browser refreshes SW?

And since we have no control over when SW updates, we're forced to maintain different versions of assets depending on what index.html is being served by SW?

**Comment by NekR** [comment]
@Hengjie if you do not use `optional` caches -- your are probably fine. Even more, if  you use only `main`  cache, then you should have no problems at all.

What I said in that comment is that deletion of old cached assets happens only when new SW becomes active, so while old one is active and may serve old assets -- they are not deleted. This means that if you have released new version, but a user is still on old version (browser didn't activate new SW yet) then user will get all needed assets from cache.

This only works fine if:

1. You do not have dynamic content in cached assets, e.g. you cache only app shell
2. You update assets all at one time, e.g. if path of script changed then it should be changed in `index.html` at a same release

That is what this plugin is for, at a moment.

**Comment by NekR** [comment]
@xlc Do you have `index.html` on CDN with a small cache time like a 5 minutes and a SW file without cache time, so your users may be get in situation where `index.html` is old but SW file is new?

**Comment by xlc** [comment]
Yes we are using CloudFront CDN have have 5 minutes cache time. Currently we keep the last old version of the files so in case user still getting old `index.html`, they won't hit 404.

**Comment by NekR** [comment]
Let's figure out this problem together. I also thought about this situation and how to solve it. 

Okay, standard best practice of the web and HTTP caching is:

Keep all previous versions of build on CDN/server, add new versions with a new tag (new folder name for example), only `index.html` updates directly. Cache to static assets set forever, cache for `index.html` is set to about 5 minutes.

This works fine until you bring ServiceWorker in game. If ServiceWorker is not cached at all in this situation, then there is chance to get new SW while getting `index.html` from cache (@xlc and @Hengjie  main concern). In this case `index.html` will still be referring to old assets, while new SW will remove them from the cache and cache new version. In a best scenario, assets will just be served from server, bypassing SW. In a worst (badly configured SW) -- requests will stuck.

So far, here are some ways I came with, which could solve it:

1)
* Set same amount of cache to `sw.js` (still possibly to get different version of `index.html` and `sw.js` because of race?)
* Keep version of build inline in `index.html` and `sw.js` and compare them on SW load (firing what? `updaterequired`?)
* What about `AppCache`?

2)
* Some CDN allows busting cache on build, so once you add files for new version and update `index.html` and `sw.js` then just clear CDN cache. 
* What about `AppCache`?

3)
* Never cache `index.html`, 'sw.js' and AppCache related files.

____________________________________________________
> I am also unsure how service worker cache works with browser cache. Because I have expires=max for all js/css/image/font files I am not sure does the cache.addAll will bypass the browser cache or I have to cache bust the urls (add query parameter).

SW doesn't bust HTTP cache by default, this means that developers should do it themselves if they are using `cache-first` network strategy.  
`offline-plugin` is using `cache-first` network strategy, but unfortunately I didn't thought about cache-busting writing it. It's now implemented in `v3` branch, but in a v2 you probably should do it yourself :(

**Comment by NekR** [comment]
Okay, with a help of Jake Archibald here are some more suggestions:

Query param on `index.html` (random value or version of build) works fine for busting HTTP cache and CDN cache (if it's not disabled on CDN). So requesting it in SW with cache-bust param should work, but it won't work in AppCache because AppCache stored files by whole url, e.g. `index.html` ins't same as `index.html?v=2` for it.

**Comment by NekR** [comment]
Thing which should work for both SW and AppCache:

* Cache `index.html` on CDN for 5 minutes. Never cache SW or AppCache files. Purge CDN's cache of `index.html` on project's new version deploy.
* In SW, use cache-bust query params (e.g. `index.html?v=10`) to bust HTTP cache (and CDN) when updating. Use ignoreSearch when matching requests in cache.
* In AppCache, use plain urls (without query, e.g. `index.html`). AppCache seems to automagically bust small browser http cache. CDN cache cannot be busted in AppCache (this is why purge CDN cache on build)
* Keep all prev version builds on a server in case of some http cache race or AppCache<->CDN versions miss-match.

Hope this helps :)

**Comment by NekR** [comment]
Turns out AppCache cannot bust even HTTP cache, so if you are using AppCache too -- you have no option other than completely disable cache for `index.html`. Probably serve it from main server and all other assets from CDN. Since `index.html` also is cacheable in SW/AppCache, only disadvantage here is that it wont be server from CDN. 

Closing this now. Seems to be solved for SW, if something, you may try use `v3` branch.

**Comment by xlc** [comment]
Thanks for the update. I will try v3 branch later when I have free time.

**Comment by v0lkan** [comment]
For the record, I had a similar issue; and worked around it by explicitly unregistering the ServiceWorker if I find a version mismatch ( [link to relevant file on my project](https://github.com/jsbites/bytesized.tv.web/blob/763d10021d9e5be1641a0b0cc8f1eb5795ae7a91/src/lib/offline.js)  )

```
const checkIfAppIsStale = () => {
    if ( !serviceWorkerUnregisterAvailable ) { return; }

    get( `/version.txt?r=${Math.random()}` )
        .then( ( res ) => res.text() )
        .then( ( text ) => {
            if ( text && text.trim() === process.env.VERSION.trim() ) { return; }

            navigator.serviceWorker.getRegistrations().then( ( registrations ) => {
                for ( const registration of registrations ) {
                    registration.unregister();
                }
            } );
        } );
};

checkIfAppIsStale();
```

Where `version.txt` is never cached, so any mismatch means that the sw cache is lagging behind, so I kill the sw without mercy :)

Excellent plugin; great time-saver.

Ah before I forget; @NekR: Any ETA on `ignoreSearch` and other nifty utils being merged to the master?

Cheers,

Volkan.

**Comment by NekR** [comment]
@v0lkan this issue is pretty old and I'm now sure what it's about tbh. There is `responseStrategy: 'network-first'` option now which loads assets from the network first and if it fails, loads them from the cache.

I also don't see why there could be problem with cache/SW updates because I and other people do not have them with current version of `offline-plugin`.

About `ignoreSearch`, there is no way to specify it but it's automatically applied to all assets generated by webpack. External assets still don't have `ignoreSearch` and I'm not sure when there will be such functionality.

**Comment by v0lkan** [comment]
Got it. — Thanks for the information Arthur.

**Comment by v0lkan** [comment]
> I also don't see why there could be problem with cache/SW updates because I and other people do not have them with current version of offline-plugin.

Probably due to some weird race condition going on in CloudFront/S3/AWS or somewhere in between.

For what it’s worth, my entry point (index.html) gets served from the cache unless I explicitly kill the service worker (with the above snippet)

It migh very well be a timeout issue, and if I wait long enough, or if I restart chrome or reboot my system etc, it might update itself. — Not sure — If it’s just me who’s (still) having this problem, don’t worry.

**Comment by NekR** [comment]
> For what it’s worth, in my case, my entry point (index.html) was getting served from the (ServiceWorker’s) cache unless I explicitly kill the service worker (with the above snippet)

That's fine, it supposed to work that way. Why do you need to kill it?

> It migh very well be a timeout issue, and if I wait long enough, or if I restart chrome or reboot my system etc, it might update itself. — Not sure — If it’s just me who’s (still) having this problem, don’t worry.

I don't think you have any problems here 🙂, just check out this guide https://github.com/NekR/offline-plugin/blob/master/docs/updates.md

**Comment by NekR** [comment]
> I can, of course hack the generated sw.js to do something specific to my use-case, but that would be ugly. — I’ll fork the repo and play it it further if Ihave time, maybe I can come up with a valuable contribution.

I still don't understand what exactly you are trying to do. What is it?

**Comment by v0lkan** [comment]
> That's fine, it supposed to work that way. Why do you need to kill it?

Because my index.html has changed (because I deployed a new version) but closing all the tabs, killing chrome, and reloading the page, cmd+refreshing the page, refreshing the page… etc… etc… ws still loaded the old index.html. — It might be due to sw.js being cached too, I need to check that.

I’ll checkout the guide, and retry it with a sane mind tonight. — Maybe it’s just gremlins walking in my servers smaking things weirder than they need to be :)

**Comment by NekR** [comment]
>  It might be due to sw.js being cached too, I need to check that.

Yes, that's the only possible reason then. Always server `sw.js` with `Cache-Control: no-store`.

Let me know if it works or not :-)

**Comment by v0lkan** [comment]
> Let me know if it works or not :-)

Will do.

**Comment by v0lkan** [comment]
So what I did

* Used `http-server` Node.JS global app with 10 seconds cache time
* Made sure that I waited 30 seconds between every refresh etc.
* Enabled cache from dev tools so that I can keep dev tools open w/o interfering anything
* Loaded the page
* Index page with `alert(1)` is displayed (expected)
* Updated sw version
* Updated index.html; set `alert(2)`
* Closed the tab.
* Waited for 30 seconds (just in case)
* Opend another tab
* pased the link
* observed that the page loads new service worker (by checking the version in the source code)
* CMD+R
* regular refresh
* another CMD+R
* another regular refresh
* CMD+R then CMD+R
* (… all other 4 combations of CMD+R and “regular refresh”'; waiting for 30 seconds between each operation

What happened: I still got `alert(1)` instead of `alert(2)`.

Side notes:

* The script that unregistered the service worker worked for me all the time.
* There’s a `/index.html` to `/` mapping in `pathRewrite`; I’m starting to suspect that part, though I’m not sure.
* I haven’t tried the `network-first` strategy since it, kind of, defies the purpose of caching (assume you are on a 2G network that barely streams data and you are tring to fetch the asset from the network first; whereas it would have come from the cache in a heartbeat)

* I see the the script is refreshing all the assets whose filename has changed. Since index.html is the same, it just does a blind “move asset”

```
from console log:
[SW]: Changed assets: main
[SW]: Moved assets: main
…
 lots of assets
 …
Asset: Array[2]
    0: "https://byte-sized-tv-web-new-vozcelik.c9users.io/" #this is actually /index.html remapped internally.
    1: "https://byte-sized-tv-web-new-vozcelik.c9users.io/"
sw.js:3 [SW]: Activate event
Delete cache: webpack-offline:0.8.16
```

So my understanding is, service worker deletes the old cache; creates a brand new cache while moving index.html from the older cache bag, to the newer one.

…

So that’s my case.

For the record again this gist <https://gist.github.com/v0lkan/c714a76de48420b264a7db917510f5d9> solves my problem for good.

Though I’m not sure why it’s not working as it’s described in the article. — Maybe it’s something to do with my environment; browser; a company policy on my machine, I don’t know :)

**Comment by NekR** [comment]
> I see the the script is refreshing all the assets whose filename has changed. Since index.html is the same, it just does a blind “move asset”

Nope, it updates an assets if its hash changed, not name. Even if you have different names but the same hash of the file, `offline-plugin` is being able to detect if that's the same fine, and vice-versa if not.

For external assets that procedure isn't performed because their hashes aren't available.

Anyway, you are just doing thing in a wrong order, this is the correct one:

* Used `http-server` Node.JS global app with 10 seconds cache time
* Made sure that I waited 30 seconds between every refresh etc.
* Enabled cache from dev tools so that I can keep dev tools open w/o interfering anything
* Loaded the page
* Index page with `alert(1)` is displayed (expected)
* Updated sw version
* Updated index.html; set `alert(2)`
* Reloaded the tab
* Waited for SW to update
* Closed the tab.
* Waited for 30 seconds (just in case)
* Opened another tab
* Got `alert(2)` as expected

**Comment by NekR** [comment]
Also, when we will figure this out we'll be to move to `offline-plugin`'s events: https://github.com/NekR/offline-plugin/blob/master/docs/runtime.md#install-options which should eliminate the need of your snippet.

**Comment by v0lkan** [comment]
Let me try with that order.

**Comment by v0lkan** [comment]
Okay, so good news :)

It worked as defined.

The reasons of it not working in my former case was that I needed some coffee :)

Seriously though, I was being “clever” by just updating the “version” on the generated sw.js file manually, without touching the `hashesMap` section which is a hashmap of assets to track.

So when I did my changes through webpack (i.e. changing index.ejs and generating a new index.html etc) with a short-term cached, it worked as expected. — I’ll remove my hack and try again on a more production-like use-case to see if it works okay too.

**Comment by v0lkan** [comment]
note I used both cacheStrategy "all" and "updated", and the result was positive 👍

**Comment by NekR** [comment]
@v0lkan great! Also check this section about `offline-plugin` events: https://github.com/NekR/offline-plugin/blob/master/docs/updates.md#config, it might be helpful if you wanted to apply updates faster, control them, etc.

**Comment by v0lkan** [comment]
Sure I’ll check the config section; since I can attach to events I probably don’t need to use my snippet.

Though, I’ll still use an identical strategy  for the paranoid users who never close their tabs. By definition, service worker will not register itself unless you close all the tabs you know.

Thanks for all the help.

Have a great night.

**Comment by NekR** [comment]
That's why you may need `runtime.applyUpdate()` which forces update even if tabs are open. Also there is `autoUpdate` option for paranoid users who never close their tabs 😉

What I'm trying to say is that there is already a lot of functionality in `offline-plugin` itself so you probably don't need all your hacks. But well, if those hacks work for you, then that's fine too :-)

**Comment by v0lkan** [comment]
Totally agree with that; [I love wheel-reinvention](http://blog.geekli.st/post/111932989787/grab-your-chisel-and-start-pounding-a-guest), but I’m also a pragmatist ;)  — My hacked saved my day, and I’ll for sure use `runtime.applyUpdate()` and its sister events etc to make it work “by the book”.

As a tangential note; here how Chrome makes a request to sw.js

```
curl 'https://bytesized.tv/sw.js' \
	-H 'Referer: https://bytesized.tv/sw.js' 
	-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' \
	--compressed
```

which means, it will always request the latest and greatest version from the origin server.

So as long as `sw.js` is **not** cached on the origin, it will properly update itself.
