### ISSUE TITLE
Caching webpack output assets when assets are served over a CDN

### ISSUE THREAD

**Issue by tconroy** [NekR/offline-plugin#246]
Hey there,
more Service Worker examples assume that static assets (JS bundle, CSS bundle, images) are being served from the application server, and so are configured to cache assets from the same origin.

However, in many production-level apps, your static assets are served from a CDN. For example, I have a react app that builds the assets via webpack, rsync's the assets to a CDN, including the proper asset link in a dynamically generated page template.

How would we accomplish that kind of caching with this plugin?

**Comment by NekR** [comment]
@tconroy Hey. If you know your CDN URL upfront, e.g. it's not dynamic, then you can rewrite asset urls on built time. Also make sure CDN returns assets with proper CORS headers, otherwise that won't work.

You need `rewrites` option for that. See here how built-in one looks like: https://github.com/NekR/offline-plugin/blob/master/src/index.js#L29

**Comment by NekR** [comment]
@tconroy hey, did it help? Should I close this issue or you still have problems with it?

**Comment by tconroy** [comment]
Hi @NekR , thanks I think this helps. So we'd want to use the rewrites option for dist builds, and just not set it during local dev ( since it'll be served locally / with the app server ). Seems reasonable.

Thanks!

**Comment by NekR** [comment]
Great, thanks for info! 👍
