### ISSUE TITLE
Does `excludes` support negate patterns?

### ISSUE THREAD

**Issue by whitecolor** [NekR/offline-plugin#406]
Does `excludes` option support negate patterns?

```
excludes: ['**/icons-*/*', '!**/icons-*/some-icon-*'],
```
to exclude evertying from `/icons-*` but `some-icon-*`?

**Comment by GGAlanSmithee** [comment]
@whitecolor 

Sorry for the late reply.

The `excludes` functionality uses [`minimatch`](https://github.com/isaacs/minimatch) which does allow for negate patterns. However, each entry in the `excludes` array is evaluated seperatley, which means that in your case, all icons would (probably) be included since the first pattern matches all files in that directory (please do try it to verify).

To get the desired behaviour, you would have to supply **one** pattern which returns all icons except for the one you would like to exclude. I am in no means an expert on this, so wether this is possible, and how that expression would be written, I could not tell you. However, if you find a way, please let us know, and I will incorporate it in the docs.
