### ISSUE TITLE
ERROR in OfflinePlugin: Plugin's runtime wasn't added to one of your bundle entries. See this https://goo.gl/YwewYp for details.

### ISSUE THREAD

**Issue by marcelowu** [NekR/offline-plugin#411]
I do not know where to put this line,

require('offline-plugin/runtime').install();
![default](https://user-images.githubusercontent.com/30912144/45473321-2485b380-b70d-11e8-814c-d21dfc8d3bd9.PNG)

**Comment by GGAlanSmithee** [comment]
@marcelowu 

Sorry for the late reply.

As specified in [the error message link](https://github.com/NekR/offline-plugin/wiki/Issue:-plugin-without-the-runtime) the plugin should be installed - `require('offline-plugin/runtime').install()` - in the main entry, which in your case probably is `app.js`

For example, in my app i install the service worker in the file `app/client.jsx`, which is also the webpack `entry` point.

I will close this issue, since there are a lot of similar issues that has already been answered on Github and Stack Overflow, it probably covers your case too.
