### ISSUE TITLE
Suggest add a uninstall function

### ISSUE THREAD

**Issue by ericfong** [NekR/offline-plugin#62]
The code that I used to uninstall sw

```
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.getRegistrations().then(registrations => {
      for (const registration of registrations) {
        registration.unregister()
      }
    })
    caches.keys().then(keyList => {
      return Promise.all(keyList.map(key => {
        return caches.delete(key)
      }))
    })
  }
```

**Comment by NekR** [comment]
Why exactly it's needed? There is no way to uninstall `AppCache` for example. Also calling `registration.unregister()` doesn't mean that `ServiceWorker` will became `redundant` immediately, so you _shouldn't_ clear cache at that moment. Clearing cache may result in broken page (potentially), but in case of `offline-plugin` this simply will make SW cache subsequent requests again.

**Comment by ericfong** [comment]
Sorry, I am new to this area. Just finding a way to nicely uninstall service worker and cache.

I know app-cache is hard to uninstall. So, I disabled it.

But I think we should have a way to revert the app to a normal mode in case anything happened.

Can we launch a ```sw.js``` with a empty caches first and use ```registration.unregister()``` & ```caches.delete```

Or do we have any reference steps to nicely uninstall service worker and caches?

**Comment by NekR** [comment]
> But I think we should have a way to revert the app to a normal mode in case anything happened.

What for example?

> Or do we have any reference steps to nicely uninstall service worker and caches?

There is no special way to "truly uninstall" ServiceWorker. Since SW is a scriptable thing, correct uninstallation depends on its implementation.
I think good way to handle it to send a message to SW telling it to "unregister". Then SW will put itself in inert state (will stop handling any request), will delete all its caches and then will unregister itself (`registration.unregister()`).

But I still do not see any special reason to have this API. Even if there is some sense in it, it won't be in priority in many next releases, because there are more important things right now.

But i'll keep this open and if you have any reason for this API to exists, please leave them here. Any feedback is welcome. Thanks!

**Comment by ericfong** [comment]
Thanks a lot.

Because I get some clients report that they cannot get the new version when
I setup AppCache on my own.

So, I want to try Service Worker and disable AppCache

And I found that it is pretty hard to remove a buggy AppCache (because it
throw exception in downloading assets...)

So, I wonder how can we have a mechanism to  disable all clients using
service worker before I launch it.

I think that is Edge case too. Thx for you help

On 12 June 2016 at 12:41, Arthur Stolyar <notifications@github.com> wrote:

> But I think we should have a way to revert the app to a normal mode in
> case anything happened.
>
> What for example?
>
> Or do we have any reference steps to nicely uninstall service worker and
> caches?
>
> There is no special way to "truly uninstall" ServiceWorker. Since SW is a
> scriptable thing, correct uninstallation depends on its implementation.
> I think good way to handle it to send a message to SW telling it to
> "unregister". Then SW will put itself in inert state (will stop handling
> any request), will delete all its caches and then will unregister itself (
> registration.unregister()).
>
> But I still do not see any special reason to have this API. Even if there
> is some sense in it, it won't be in priority in many next releases, because
> there are more important things right now.
>
> But i'll keep this open and if you have any reason for this API to exists,
> please leave them here. Any feedback is welcome. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NekR/offline-plugin/issues/62#issuecomment-225409873>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAOd5HXfLpeVGbQyPgHgBLhrub2nRT5Fks5qK43ngaJpZM4IuZK0>
> .
>



-- 
Best Regards,
Eric Fong

**Comment by NekR** [comment]
> I think that is Edge case too. Thx for you help

Sounds like a good reason actually. I'll think if I can do something here.

> And I found that it is pretty hard to remove a buggy AppCache (because it
throw exception in downloading assets...)

Serving 404 HTTP status for `manifest.appcache` should help I think. Have you tried it?

**Comment by ericfong** [comment]
I solve by serve a empty manifest.appcache and force download new index.html from server

and index.html should without manifest tag

But I am not sure about Service Worker. And there may be a better way.

**Comment by chaintan17** [comment]
Can you explain a bit more?
I want to completely remove serviceworker and appcache.
I want customer to no longer able to access offline.

But i don't know where to start with. Should i disable appcache or serviceworker or both of them?

Can you please advise?

**Comment by chaintan17** [comment]
I tried above code and now service worker get uninstlled.
However, Safari browser can still access my website without internet connection.
How can i disallow that? Is it because of AppCache?

**Comment by NekR** [comment]
> How can i disallow that? Is it because of AppCache?

Yes, it's because of `AppCache`. Just delete `manifest.appcache` (but leave `manifest.html`) there to remove it from browsers.

> I want customer to no longer able to access offline.

As a feature or you have problems with offline support?

**Comment by ericfong** [comment]
Personally, I disabled appcache when I use offline-plugin.

Try to respond 404 for your appcache file

**Comment by NekR** [comment]
I think I can add `uninstall` option in `v4`, just would be good to hear reason why you possibly want to disable offline-support.

@ericfong yeah, `AppCache` should go away 👍 Some people still use it though

**Comment by chaintan17** [comment]
@NekR it's because i accidently use offline plugin during development process
And now, tester cannot get latest version of my update because their device load assets from cache instead.
That's why i want to remove it completely.

**Comment by chaintan17** [comment]
response 404 work quite well,
Thanks man!

**Comment by NekR** [comment]
> That's why i want to remove it completely.

I see. Thanks for the info, @chaintan17.
I think that it would be good to have `uninstall` option or at least a doc about _how to uninstall_. Thanks all for contributing ideas 👍

**Comment by GGAlanSmithee** [comment]
I had some issues with a sw interfering when trying to run my app in dev mode. The sw made it so that hot-module-replacement would not work (the app was running in prod mode). When `ctrl+f5`, the browsers would refresh and enable HMR, but the next time I re-started the app, it would go back to using the sw.

There are probably some factors which makes this an edge case:

1. I am running the app from cloud9 IDE (so localhost is proxied via a URL using https)
2. I installed sw "locally", in production mode, for testing purposes

Anyway, I just wanted to say that the only way I could resolve this was by navigating to chrome://serviceworker-internals/ and uninstalling the sw that way. Maybe we should add this as a way to truly uninstall a sw in the documentation?

**Comment by NekR** [comment]
So you mean that you once run your project in production env on `localhost` and SW worked there. Then you switched back to development env still running on `localhost` and that previously registered SW was messing with you dev env? (assuming you have `offline-plugin` disabled in dev env)

**Comment by NekR** [comment]
@GGAlanSmithee ^

**Comment by GGAlanSmithee** [comment]
@NekR 

> So you mean that you once run your project in production env on localhost and SW worked there. Then you switched back to development env still running on localhost and that previously registered SW was messing with you dev env? (assuming you have offline-plugin disabled in dev env)

exactly!

**Comment by NekR** [comment]
@GGAlanSmithee I see. I'll think how to handle this situation. Thanks for letting me know about it!

**Comment by NekR** [comment]
@GGAlanSmithee would it help if you could install SW in development environment too, but it wouldn't handle requests, it would just be there?

**Comment by GGAlanSmithee** [comment]
@NekR I'm not sure if this is something that `offline-plugin` should handle or if it was something situational that I did which caused it. Now that I successfully uninstalled the sw, I will see if I can reproduce it.

**Comment by GGAlanSmithee** [comment]
@NekR 

I can reproduce this by:

1. uninstall sw in `chrome://serviceworker-internals`
2. run app in development mode
    * no sw installed
    * HMR (and other dev-only features) are enabled
3. run app in production mode
    * sw is installed and resources cached
4. run app in development mode
    * app looks for sw
    * cannot find cached content (is removed in a clean script)
    * HMR (and other dev-only features) are disabled
5. uninstall sw and run app in development mode and everything works again

Here is where it gets weird, because if I (instead of doing point 5) do the following;

1. clear the cache with `ctrl+f5`
2. close the tab
3. open the app in a new tab (in development mode)

then, a cached version of the production build get served, which shows the service worker events and the caching of content (in dev mode which doesn't even install the sw, and without an actual sw file)!, If I then hit `ctrl+f5` again, then the dev build gets served. I can reproduce this over and over.

This is super weird, but I cannot see what I am doing wrong. Here's some additional info:

`"offline-plugin": "^4.3.1",`
```javascript
new OfflinePlugin({
    relativePaths: false,
    publicPath: output.publicPath,

    ServiceWorker: {
        events: true,
        navigateFallbackURL: '/'
    },

    // No need to cache .htaccess. See http://mxs.is/googmp,
    // this is applied before any match in `caches` section
    excludes: ['.htaccess'],

    caches: {
        main: ['/', ':rest:'],

        // All chunks marked as `additional`, loaded after main section
        // and do not prevent SW to install. Change to `optional` if
        // do not want them to be preloaded at all (cached only when first loaded)
        additional: ['*.chunk.js', '/reset.css']
    },

    externals: ['/', '/reset.css'],

    // Removes warning for about `additional` section usage
    safeToUseOptionalCaches: true,

    AppCache: false
})
```

it builds on the [one from react-boilerplate](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.prod.babel.js#L72) and is only included in the prod build.

I have a feeling this error is caused be me running my app through cloud9 ide which servers it over https, but my knowledge of sw is very limited, so might be totally wrong.

Sorry for the lack of info. If I'm able to get some more time, I will try to create a minimal repo for you.

**Comment by GGAlanSmithee** [comment]
Thinking some more about it, I guess it isn't _that_ weird. Chrome looks for a sw, since there is one registered for that address. But shouldn't the behavior be the same for localhost then?

**Comment by NekR** [comment]
Hi @GGAlanSmithee. Sorry, I don't have time to review it at a moment. I'll take a look later today or tomorrow.

**Comment by NekR** [comment]
I fixed it as a separate project: https://github.com/NekR/self-destroying-sw

**Comment by whitecolor** [comment]
I've met a problem on recent ios 11.4 (at least it happened after iOs update). App with installed sw (with offline plugin) in standalone mode (full screen) stopped to get updated. Not sure how to debug it, and it worked only after `navigator.serviceWorker.getResitration().then(r => r.unregister())`. So have to build-in such function in the app, so user could fix this. Sw is working not very reliably on iOs.

**Comment by danny-wang** [comment]
@NekR 
Every time I update something in my code and I deploy. When a user opens my site again he'll only fetch the new service worker, but still use the old cached files. This is until he refreshes a second time...

Therefore, every time I deploy something new, ask a friend to check it out, he won't see it the first time he tries to open it...
Any ideas how to prevent this?

i hope service worker find update can prevent page show info until get new file, can use new file to render info
