### ISSUE TITLE
Caching `index.html` with `changed` update strategy

### ISSUE THREAD

**Issue by green-arrow** [NekR/offline-plugin#83]
I may be missing something simple here, but I cannot figure out how to force an update of `index.html` when using a cache strategy of `changed`. The HTML file always falls into the `moved` category. I have the `index.html` entry located in `main` as stated in the documentation. Is there something special that needs to be done to force that file to be updated?

**Comment by NekR** [comment]
Hmm.. I don't think there is a solution at a moment if `index.html` isn't part of your webpack build. `offline-plugin` uses build hash of each file to determine if it was changed. So if some internal file used, plugin cannot determine if it was updated or not, therefore it goes to `moved`.

But I guess it's also kind-of a bug, because if I don't have a hash for a file, then I should always mark it a changed (at least this was planned). I'll what is going on there.

Also there was a plan for `alwaysRevalidate` property, but unfortunately it wasn't implemented for `v3`.

**Comment by NekR** [comment]
Okay, from the code it seems everything is right: if asset isn't in hash map, then it's `changed`, not `moved`.

Can you provide a bit more info? Your `offline-plugin` config and SW output will be super useful.

**Comment by green-arrow** [comment]
@NekR - I should have posted the config originally, my bad. Additionally, the `index.html` file is part of my webpack build. As you can see below, the hash in `hashesMap` for my HTML pages doesn't change between app builds.

`config`:

```
// Pages
new HtmlWebpackPlugin({
  template: paths.client('index.html'),
  hash: false,
  filename: 'index.html',
  inject: 'body',
  chunks: ['app', 'vendor'],
  minify: {
    collapseWhitespace: true
  }
}),
new HtmlWebpackPlugin({
  template: paths.client('styleguide.html'),
  hash: false,
  filename: 'styleguide.html',
  inject: 'body',
  chunks: ['styleguide', 'vendor'],
  minify: {
    collapseWhitespace: true
  }
})

// Offline Plugin
new OfflinePlugin({
  excludes: ['**/*.map'],
  safeToUseOptionalCaches: true,
  updateStrategy: 'changed',
  caches: {
    main: ['index.html', 'app*.js', 'styleguide.html', 'styleguide*.js', 'vendor*.js'],
    additional: ['*.chunk.js']
  },
  ServiceWorker: {
    events: true
  }
})
```

Initial output:

```
[SW]: Install event
sw.js:483 [SW]: Cached assets: main
sw.js:486 Asset: http://localhost:4000/
sw.js:486 Asset: http://localhost:4000/app.76410cbedf1e56614353.js
sw.js:486 Asset: http://localhost:4000/styleguide.html
sw.js:486 Asset: http://localhost:4000/styleguide.6568743c1e1f3ae6603e.js
sw.js:486 Asset: http://localhost:4000/vendor.7b9cd2d34532a6c44991.js
sw.js:120 [SW]: Activate event
styleguide.6568743….js:347 Service worker is installed!
styleguide.6568743….js:348 Application is now ready for offline use.
```

Initial SW hash:

```
var __wpo = {
  "assets": {
    "main": [
      "./",
      "./app.76410cbedf1e56614353.js",
      "./styleguide.html",
      "./styleguide.6568743c1e1f3ae6603e.js",
      "./vendor.7b9cd2d34532a6c44991.js"
    ],
    "additional": [],
    "optional": []
  },
  "hashesMap": {
    "76410cbedf1e56614353a8fa1ee77a68": "./app.76410cbedf1e56614353.js",
    "6568743c1e1f3ae6603e214e34e8b868": "./styleguide.6568743c1e1f3ae6603e.js",
    "7b9cd2d34532a6c44991c62b7df7e13d": "./vendor.7b9cd2d34532a6c44991.js",
    "886830bd4d6b0d9ffa8042b493b16a7b": "./",
    "d5b0cb64d74627b923c977bbfadf981d": "./styleguide.html"
  },
  "strategy": "changed",
  "version": "7/6/2016, 8:06:50 AM",
  "name": "webpack-offline",
  "relativePaths": true
};
```

New app output:

```
[SW]: Install event
sw.js:483 [SW]: Changed assets: main
sw.js:486 Asset: http://localhost:4000/styleguide.f8680a20c484bb0984f7.js
sw.js:486 Asset: http://localhost:4000/vendor.9daf38d23e4c600d79a0.js
sw.js:483 [SW]: Moved assets: main
sw.js:486 Asset: ["http://localhost:4000/app.76410cbedf1e56614353.js", "http://localhost:4000/app.76410cbedf1e56614353.js"]
sw.js:486 Asset: ["http://localhost:4000/", "http://localhost:4000/"]
sw.js:486 Asset: ["http://localhost:4000/styleguide.html", "http://localhost:4000/styleguide.html"]
styleguide.6568743….js:351 New version of application available, applying update now.
sw.js:120 [SW]: Activate event
sw.js:256 [SW]: Delete cache: webpack-offline:7/6/2016, 8:06:50 AM
styleguide.6568743….js:358 Application update succeeded!
```

New app SW hash:

```
var __wpo = {
  "assets": {
    "main": [
      "./",
      "./app.76410cbedf1e56614353.js",
      "./styleguide.html",
      "./styleguide.f8680a20c484bb0984f7.js",
      "./vendor.9daf38d23e4c600d79a0.js"
    ],
    "additional": [],
    "optional": []
  },
  "hashesMap": {
    "76410cbedf1e56614353a8fa1ee77a68": "./app.76410cbedf1e56614353.js",
    "f8680a20c484bb0984f78c30128b5443": "./styleguide.f8680a20c484bb0984f7.js",
    "9daf38d23e4c600d79a02fee7b1e8b8e": "./vendor.9daf38d23e4c600d79a0.js",
    "886830bd4d6b0d9ffa8042b493b16a7b": "./",
    "d5b0cb64d74627b923c977bbfadf981d": "./styleguide.html"
  },
  "strategy": "changed",
  "version": "7/6/2016, 8:07:47 AM",
  "name": "webpack-offline",
  "relativePaths": true
};
```

**Comment by NekR** [comment]
@green-arrow hmm.. seems like problem could be in `HtmlWebpackPlugin`, but I'm not sure though. Some time ago, in its source code, I saw that it computed hash **before** template is evaluated, e.g. the hash is computed from bytes of template itself.

@jantimon can you help us here with figuring out what is going on? If it's better, I can file an issue on `HtmlWebpackPlugin` repo.

**Comment by NekR** [comment]
I think I'm right, template is execute after compilation: https://github.com/ampedandwired/html-webpack-plugin/blob/8fbbf69e503ce637c7ac92601afea02caff8ebcb/index.js#L135

Of course, I can have a special case and run hash computation of `.html` files on my own, but this is bad that hash doesn't include dynamic content anyway.

**Comment by green-arrow** [comment]
Yeah, I think doing a special hash computation on your own is more of a bandaid. Is the correct thing to file an issue with `HtmlWebpackPlugin` then?

**Comment by NekR** [comment]
@green-arrow Let's wait a bit if @jantimon can answer here. If not, I'll file an issue there.

**Comment by NekR** [comment]
@green-arrow as a temporal solution, you can try to add all `.html` files to `excludes` and then manually add them to `externals` and `caches`. The magic here is that excludes runs first before anything is computed   /used by plugin, so this could work, but I am not sure 100%.

I am from a phone now, so unfortunately cannot show full example of it.

**Comment by green-arrow** [comment]
@NekR - no worries, I'm not in any kind of a rush. We only have a couple files that are cached, so when the app updates, all the files should be revalidated anyway, so I'm just using the `all` strategy. Eventually we will need more fine-grained control via `changed`, which is why I opened the issue :)

**Comment by jantimon** [comment]
What can I do to support this?

**Comment by NekR** [comment]
@jantimon Okay, let me explain how I extract hashes. It's basically this method: https://github.com/NekR/offline-plugin/blob/master/src/index.js#L383

The idea is to run on `compilation.chunks` first and if chunk already has a `hash`, then use it. If chunk doesn't have a hash, it just generated it later from assets's `source`: https://github.com/NekR/offline-plugin/blob/master/src/index.js#L376

I'm not particularly sure how `HtmlWebpackPlugin` works right now, but as far as I get from source code you do child compilation and use its hash for caching and only after that you are executing templates/plugins. It seems very reasonable since you probably don't want to cache plugins/templates results.

Right now I see only 2 solution here:

1) I ignore `HtmlWebpackPlugin` generated entries in chunks array and just compute their cache from `compilation.assets`
2) `HtmlWebpackPlugin` somehow makes its entries have correct hash, e.g. based on final asset output bytes

I understand that option "2" probably means massive rewrite, therefore I'm completely fine with option "1".

Under question is the meaning of `compilation.chunks[*].hash` in a webpack world: is it supposed to mean final chunk's output hash? If not, why and what should have final chunk?

I would be good to ask `sokra` itself about it, but he doesn't tend to ask in such discussions, so I guess that we have to decide on our own.

**Comment by jantimon** [comment]
Webpack has so many hashes so I don't know what you mean by final hash.

I don't know if I understood correctly what you need but you can read and modify all assets which will be injected into the page using the `html-webpack-plugin-alter-asset-tags` event:

```js
function YourPlugin() {

}

YourPlugin.prototype.apply = function apply(compiler) {

  function filterTag(tag) {
    // Maybe this part won't be necessary for you
    return tag.tagName === 'link' && tag.rel === 'stylesheet';
  }

  function processTag(tag) {
    console.log(tag);
  }

  compiler.plugin('compilation', function compilationPlugin(compilation) {
    compilation.plugin('html-webpack-plugin-alter-asset-tags', function supportHtmlWebpack(pluginArgs, callback) {
      pluginArgs.head.filter(filterTag).forEach(processTag);
      pluginArgs.body.filter(filterTag).forEach(processTag);
      callback(null);
    });
  });
};

module.exports = YourPlugin;
```

**Comment by NekR** [comment]
Final hash of a file is the hash of bytes you output, i.e. of this: https://github.com/ampedandwired/html-webpack-plugin/blob/e493064c34df9a118a0dd307f862ac69fca2fd8c/index.js#L174
It's final because you don't do modifications to content of that file after it.

> I don't know if I understood correctly what you need but you can read and modify all assets which will be injected into the page using the html-webpack-plugin-alter-asset-tags event:

I already have access to `compilation.assets` as any other plugin so I definitely don't need this. 

Okay, I think I'll just start calculating hash of `HtmlWebpackPlugin ` generated files on my own and ignore its chunks.

**Comment by NekR** [comment]
@green-arrow Hi, can you try now if it works for you (install from `master`)?

**Comment by green-arrow** [comment]
@NekR - Sorry for the delayed response, had a pretty busy weekend. I just tried with `master` and it is correctly changing the `html` pages between app builds now 😄

**Comment by NekR** [comment]
Great! I'll publish it on npm now :-)

**Comment by green-arrow** [comment]
Thanks @NekR and @jantimon!
